# site settings
title: BIMO'S
subtitle: Personal Website
email: bimoaryo@rocketmail.com
description: Bimo's personal website
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 
city: Jakarta Selatan
state: DKI Jakarta
zip_code: 
country: Indonesia
phone: 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 4

# social settings
500px_url:
facebook_url: 
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: https://instagram.com/squillliams
linkedin_url: https://www.linkedin.com/in/bimo-aryo-tyasono
pinterest_url:
slack_url:
twitter_url: 
youtube_url: https://www.youtube.com/c/BimoAryoT

# build settings
markdown: kramdown

sass:
  style: compressed
