# site settings
title: BIMO TYASONO
subtitle: Personal Website
email: tyasono@icloud.com
description: Explore my voice-over portfolio, catch up on my latest movie and book reviews, or delve into my personal blog. Let's connect for collaborations or just to say hi!. For business inquiry, DM on <a href="https://instagram.com/squillliams">IG</a> or contact me through the <a href="#contact">email form</a>
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 
city: Jakarta Selatan
state: DKI Jakarta
zip_code: 
country: Indonesia
phone: 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 4

# social settings
500px_url:
facebook_url: 
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: https://instagram.com/squillliams
linkedin_url: https://www.linkedin.com/in/bimo-tyasono
pinterest_url:
slack_url:
twitter_url: https://www.twitter.com/squilliams
tiktok_url: https://www.tiktok.com/@squillliams
youtube_url: https://www.youtube.com/c/BimoTyasono

# build settings
markdown: kramdown

sass:
  style: compressed
